services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: url_shortener_ruby_development
      POSTGRES_PASSWORD: url_shortener_ruby_development
      POSTGRES_DB: url_shortener_ruby_development
    ports:
      - "5432:5432"
  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: url_shortener_ruby_test
      POSTGRES_PASSWORD: url_shortener_ruby_test
      POSTGRES_DB: url_shortener_ruby_test
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
volumes:
  db_data:
  test_postgres_data:
