services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: url_shortener_ruby_development
      POSTGRES_PASSWORD: url_shortener_ruby_development
      POSTGRES_DB: url_shortener_ruby_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: url_shortener_ruby_test
      POSTGRES_PASSWORD: url_shortener_ruby_test
      POSTGRES_DB: url_shortener_ruby_test
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
  ticket_service_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ticket_service_development
      POSTGRES_PASSWORD: ticket_service_development
      POSTGRES_DB: ticket_service_development
    ports:
      - "5434:5432"
    volumes:
      - ticket_service_db_data:/var/lib/postgresql/data
  ticket_service_db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: ticket_service_test
      POSTGRES_PASSWORD: ticket_service_test
      POSTGRES_DB: ticket_service_test
    ports:
      - "5435:5432"
    volumes:
      - ticket_service_db_test_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./lib/config/redis.conf:/usr/local/etc/redis/redis.conf  # Mount redis.conf from config
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]  # Use custom redis.conf
    restart: always
volumes:
  db_data:
  db_test_data:
  ticket_service_db_data:
  ticket_service_db_test_data:
  redis_data:
    driver: local
